### ISSUE TITLE
ods_osm and TYPO3 9

### ISSUE THREAD

**Issue by sir-gawain** [bobosch/ods_osm#36]
I ported ods_osm to TYPO3 9. You can find this version in my fork.
It can probably run in T3 8 too, but i did not test this.

ods_osm_ttcontent and ods_osm_cal also need fixed but i didn't find repositories for these.

**Comment by Atsyn** [comment]
@sir-gawain i found a problem in your version: https://github.com/sir-gawain/ods_osm
TYPO3 9 working from composer in priority. Thats mean in you version must be a `composer.json` file.
Please update your fork.

**Comment by sir-gawain** [comment]
I imported the composer.json from franzkugelmann. I do not use it, so please test, if it works.

**Comment by Atsyn** [comment]
@sir-gawain I'm so sorry but I can't do it. I'm already rewrite a lot of part in your extension because it can't work in the current state.
For example:
File: .../ods_osm/Classes/Controller/PluginController.php
Part of MM relation, it's my working code: https://monosnap.com/file/tl44Hl7U94JagQsVl5jLPOdcbD83TZ
You can compare it with your code.

I don't want saying bad about your work, it's great that guys like you do that. But it should be more careful.
Right now you extension can't work((

**Comment by sir-gawain** [comment]
I remember now. I started fixing the backend stuff and made it working for my needs and the plugin works so far as i needed it. Then the priorities changed and i did not finished it. Feel free to send me your files or pull request. Sorry about this.

**Comment by tgdbepe4** [comment]
Hi all 
I hope that ods_osm will come alive again for typo3 V9. It is a very good and helpful tool for many maps.

**Comment by albig** [comment]
I think the current version is now working with TYPO3 9.5.
