### ISSUE TITLE
TYPO3 v11 compatibility?

### ISSUE THREAD

**Issue by konradmichalik** [bobosch/ods_osm#83]
Hello,

will be a TYPO3 v11 extension version available soon?

Thanks

**Comment by mschwemer** [comment]
Startet an upgrade in my fork. 

Leaflet with Mapnik and address records "works on my machine" :tm:  also with "TYPO3 composer installers v4)

*ToDo*

* Testing (and improving)  library "Leaflet" with other layers
* Testing (and improving) all other libraries with their layers
* Testing (and improving) all the record types (fe_users, fe_usergroups, track, vector, ... )
* Provide php8 compatibility

For current progress see: https://github.com/mschwemer/ods_osm/tree/v11_compat

PRs and comments welcome :-) All changes will come the main repo (if accepted ;-) )

**Comment by mschwemer** [comment]
In order to cover all cases, I have a few questions.

1) It is possible to select page records in the plugin. What's needed to show them as a marker?
2) I need a kml file to test the track feature. (GPX works). Can somebody provide one? (The exports from google maps did not work)
3) I could not get the "Staticmap" work. Would do I need for testing?
4) The OpenLayer Library only loads the tiles after changing the zoom factor in FE. Is this a known issue?

Other than that, the extension works, even with php8.

**Comment by albig** [comment]
Thank you for your work. 

1. I've just started to setup a DDEV system with ods_osm and TYPO3 10 inside. So you can reproduce the features easily (as far, I know them ;-)). I think, tomorrow, I'm ready with it.
2. I have a KML-file and if I remember right, it worked as expected. I'll add it to the DDEV.
3. I see. The path `uploads/tx_odsosm/map` isn't created anymore on installation. This feature of TYPO3 extensions is gone (#[88525](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-88525-RemoveCreateDirsDirectiveOfExtensionInstallationEm_confphp.html)). This might be the reason.
4. Yes, It's known and due to the very old OpenLayer v2. That's another task, I would like to fix some day and upgrade to a recent OpenLayers version. https://github.com/bobosch/ods_osm/issues/52

**Comment by albig** [comment]
In the meantime, I uploaded a DDEV project repository with ods_osm on TYPO3 10.4, using the introduction and bootstrap package. 
This way, you could follow some configurations with ods_osm: https://github.com/albig/ddev-ods-osm
