### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by mysailing** [bobosch/ods_osm#93]
maps are not responsive .... any plans to change this?
Thx; Gerd

**Comment by albig** [comment]
You can set `width` and `height` of the `<div id="map">` in the flexform of the plugin. 

E.g. instead of default width "800" (px) you can set "80vw" (for 80% of the viewport width) and vor height "80vh". Of course this works only, if your page itself is responsive.

Does this work for you? If not, what do you need else?

**Comment by mysailing** [comment]
This works perfectly - could have though about it as well ;-)
thx for the hint
Gerd
